### PR TITLE
Update Action.PHYSICAL Javadoc to represent action

### PR DESCRIPTION
**Pull request by rmsy**
"Ass-pressure" isn't helping anyone.

**This is a re-submission of [#789](https://github.com/Bukkit/Bukkit/pull/789).**

### CODE REVIEW

**Comment by Wolvereness** [comment]
This change makes me sad...
Also, it's not correct, as there are more PHYSICAL interactions than pressure plates. If it's going to get changed, it needs to be made correct.

**Comment by EdGruberman** [comment]
So sad... probably the best Javadoc in the project to date.  Are you sure you can't keep some parts of the description even for _posteriority_'s sake?

**Comment by rmsy** [comment]
> Also, it's not correct, as there are more PHYSICAL interactions than pressure plates. If it's going to get changed, it needs to be made correct.

What are they? I can't seem to find any...

> So sad... probably the best Javadoc in the project to date. Are you sure you can't keep some parts of the description even for posteriority's sake?

I don't see anything wrong with the humor, haha, I just came across the documentation and was left with _no idea_ what it represented.

**Comment by SnoFox** [comment]
:[ :-1: 

Anyway, when I came across this doc, "Ass-pressure" worked for me. I knew exactly what it meant, but I've also met a few people who were confused. Additionally, this action is used for tripwire if I remember correctly.

**Comment by SagaciousZed** [comment]
It's true that people have been confused. However, I would like for the PR to be more fully fledged and descriptive before I pull it.

**Comment by SagaciousZed** [comment]
Closed due to inactivity, If you wish to submit a proper fix, feel free to get in touch with me to open this again.

**Comment by LaxWasHere** [comment]
I thought ass pressure was a way to set a players velocity.

**Pull request closed without merging**
