### PR TITLE
Update AsyncPlayerChatEvent.java

### PR DESCRIPTION
**Pull request by tmazeika**
There should not be a comma between "thread" and "but", as in "anything but that".  There should also be "an" between "by" and "incoming packet".

### CODE REVIEW

**Comment by tmazeika** [comment]
Quick question, Wolvereness.  Is it necessary for me to add a description to simple errors like this?

**Comment by Wolvereness** [comment]
As long as it's a correct change, and the commit message doesn't say something horrible, it's fine.

**Comment by Wolvereness** [comment]
Considering the intended meaning, replacing `but` with `sans` is more appropriate than removing the comma.

**Comment by Wolvereness** [comment]
It's incorrect when using `sans` without the original comma.

**Comment by tmazeika** [comment]
Apologies.  I've updated the PR again.  And sorry for the misspelling in the PR summary...

**Pull request merged**
