### PR TITLE
Expand javadocs for all 3 command pre-processing events

### PR DESCRIPTION
**Pull request by riking**
I fully expect to have screwed up the formatting.

Browser screenshot of the rendered javadoc page: http://i.imgur.com/m4PSqmn.png

### CODE REVIEW

**Comment by Wolvereness** [comment]
Please reformat your lists to mimic those found in https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/plugin/PluginDescriptionFile.java. This includes things in code tags and other literal examples (code tag indicating an exact token).

**Comment by Wolvereness** [comment]
Your list-item-wrap indention is still wrong. You also removed &lt;code&gt; tags when I meant for you to add more... See https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/plugin/PluginDescriptionFile.java#L294

**Comment by Wolvereness** [comment]
Are the appropriate changes going to be made for this PR?

**Comment by riking** [comment]
Yes, I'll do it tonight

**Comment by natemort** [comment]
@riking Long night? :p

**Pull request merged**
